version: '3'
services: 
  gogs:
    image: gogs/gogs:latest
    container_name: gogs_v1
    restart: always
    volumes:
      - /var/gogs:/data
    ports:
      - "22:22"
      - "3000:3000"  
    networks:
      net:
        aliases:
          - gogs

  postgres:
    image: postgres:9.6
    container_name: postgres_v1
    restart: always
    ports:
        - 5432:5432
    command: -c 'max_connections=200'
    networks:
      net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=rzkc
    volumes:
      - /var/postgres:/var/lib/postgresql/data

networks:
  net:
